
project_id = "dgtralqrsgmtqlyiivej"

[functions.generate-pdf]
verify_jwt = false

[functions.openai-suggest]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.parse-cv]
verify_jwt = true

[functions.initialize-paystack-transaction]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false
