// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgtralqrsgmtqlyiivej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRndHJhbHFyc2dtdHFseWlpdmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDI0MTYsImV4cCI6MjA2NTUxODQxNn0.W3cjHDNYMy7BuchBAKdVlPCgCI5vqjdhwfbg04JSge8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);